version: "3"

services:
  nginx-graduate:
    image: nginx
    container_name: nginx-graduate
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm-graduate
    networks:
      app-network:
        ipv4_address: "176.20.0.2"

  php-fpm-graduate:
    build:
      context: ./docker
      dockerfile: ./php/Dockerfile
      args:
        username: ${DOCKER_USER}
        useruid: ${DOCKER_UID}
    container_name: php-fpm-graduate
    volumes:
      - .:/var/www
    environment:
      PHP_IDE_CONFIG: serverName=graduate-docker
    networks:
      app-network:
        ipv4_address: "176.20.0.3"

  postgres-graduate:
    image: postgres
    restart: always
    tty: true
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgres/
    ports:
      - "5433:5432"
    networks:
      app-network:
        ipv4_address: "176.20.0.4"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      app-network:
        ipv4_address: "176.20.0.5"

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "176.20.0.0/16"

volumes:
  dbdata:
    driver: local
